export const menuData = [
  {
    id: 'dish-1',
    name: 'Doro Wat',
    price: 18.50,
    category: 'Meat',
    spicy: true,
    description: 'Slow-simmered tender chicken in rich berbere sauce with caramelized onions and a hard-boiled egg.',
  },
  {
    id: 'dish-2',
    name: 'Special Kitfo',
    price: 19.95,
    category: 'Meat',
    spicy: true,
    description: 'Minced prime lean beef warmed in spiced clarified butter (niter kibbeh) and fiery mitmita spice.',
  },
  {
    id: 'dish-3',
    name: 'Sizzling Beef Tibs',
    price: 17.50,
    category: 'Meat',
    spicy: false,
    description: 'Tender beef cubes sautéed with sweet onions, garlic, fresh rosemary, and mild bell peppers.',
  },
  {
    id: 'dish-4',
    name: 'Beyaynetu (Veggie Platter)',
    price: 16.50,
    category: 'Vegetarian',
    spicy: false,
    description: 'Vibrant vegetarian combination platter of yellow split peas, misir wat, gomen, and cabbage.',
  },
  {
    id: 'dish-5',
    name: 'Shiro Tegabino',
    price: 14.00,
    category: 'Vegetarian',
    spicy: true,
    description: 'Rich spiced chickpea and split pea flour stew, served bubbling hot in a clay pot.',
  },
  {
    id: 'dish-6',
    name: 'Gomen (Collard Greens)',
    price: 12.50,
    category: 'Vegetarian',
    spicy: false,
    description: 'Fresh collard greens steam-cooked with onions, garlic, ginger, and aromatic spices.',
  },
  {
    id: 'dish-7',
    name: 'Crispy Veggie Sambusa',
    price: 7.50,
    category: 'Appetizers',
    spicy: false,
    description: 'Golden, flaky pastry triangles filled with seasoned lentils, green peppers, and herbs.',
  },
  {
    id: 'dish-8',
    name: 'Kategna with Ayib',
    price: 8.50,
    category: 'Appetizers',
    spicy: true,
    description: 'Toasted injera glazed with hot berbere and spiced butter, paired with fresh cottage cheese.',
  },
  {
    id: 'dish-9',
    name: 'Traditional Coffee Ceremony',
    price: 6.00,
    category: 'Beverages',
    spicy: false,
    description: 'Freshly roasted and brewed Ethiopian Arabica coffee served with lightly salted popped corn.',
  },
];

export default menuData;
